export type Locale = 'pl' | 'en' | 'ru';
export const dictionary = {
 pl: { nav:['Menu','O Kitsune','Kontakt'], order:'Zamów na Wolt', eyebrow:'KUCHNIA AZJATYCKA · BIAŁYSTOK', title:['Azja bliżej,','niż myślisz.'], intro:'Sushi, rozgrzewające zupy i dania z woka. Znajdź swój ulubiony smak przy Warszawskiej 1A lub zamów do domu.', explore:'Odkryj menu', call:'Zadzwoń do nas', strip:['SUSHI','WOK','RAMEN','TOM YUM'], menuLabel:'CO MASZ OCHOTĘ ZJEŚĆ?', menuTitle:'Dobry smak. Twój wybór.', menuIntro:'Kilka propozycji z naszej karty. Pełne menu, aktualne ceny i dostępność znajdziesz na Wolt.', categories:['Wszystko','Sushi','Wok','Zupy','Przekąski'], aboutLabel:'KITSUNE ASIA', aboutTitle:'Jeden stół. Wiele smaków.', about:'Od łososia i chrupiącej tempury po pad thai z limonką i aromatyczny tom yum. Wybierz coś dla siebie lub podziel się sushi przy wspólnym stole.', gallery:'Smaki Kitsune', photo:'Zdjęcia opublikowane w wizytówce Kitsune na Restaurant Guru.', visitLabel:'WPADNIJ DO NAS', visitTitle:'Widzimy się w Białymstoku.', address:'Adres', phone:'Telefon', directions:'Wyznacz trasę', hours:'Godziny dostaw na Wolt', weekdays:'Poniedziałek–czwartek', weekend:'Piątek–niedziela', hoursNote:'Godziny na miejscu mogą się różnić. Zadzwoń przed wizytą.', faqTitle:'Przed pierwszym kęsem.', faqs:[['Jak zamówić dostawę?','Przejdź do naszej karty na Wolt. Tam sprawdzisz dostępność dostawy, pełne menu i czas oczekiwania.'],['Jak zarezerwować stolik?','Zadzwoń pod numer +48 515 299 000 i zapytaj o dostępność stolików.'],['Gdzie sprawdzić alergeny?','Przed zamówieniem zapytaj obsługę o składniki i alergeny. Informacje o daniach są też dostępne na Wolt.']], footer:'Sushi, wok i azjatyckie smaki w Białymstoku.', demo:'Koncepcja strony · PlexRS', priceNote:'Ceny według publicznego menu Wolt. Sprawdź aktualną ofertę przy zamówieniu.', skip:'Przejdź do treści', language:'Język', fullMenu:'Pełne menu na Wolt' },
 en: { nav:['Menu','About Kitsune','Contact'], order:'Order on Wolt', eyebrow:'ASIAN KITCHEN · BIAŁYSTOK', title:['Asia, closer','than you think.'], intro:'Sushi, warming soups and dishes from the wok. Find your favourite flavour at Warszawska 1A, or order to your door.', explore:'Explore the menu', call:'Call us', strip:['SUSHI','WOK','RAMEN','TOM YUM'], menuLabel:'WHAT ARE YOU CRAVING?', menuTitle:'Great flavour. Your choice.', menuIntro:'A few favourites from our menu. Visit Wolt for the full selection, current prices and availability.', categories:['All','Sushi','Wok','Soups','Starters'], aboutLabel:'KITSUNE ASIA', aboutTitle:'One table. Many flavours.', about:'From salmon and crisp tempura to pad thai with lime and fragrant tom yum. Find something for yourself, or share sushi around the table.', gallery:'A taste of Kitsune', photo:'Photos published on Kitsune’s Restaurant Guru listing.', visitLabel:'COME FIND US', visitTitle:'See you in Białystok.', address:'Address', phone:'Phone', directions:'Get directions', hours:'Wolt delivery hours', weekdays:'Monday–Thursday', weekend:'Friday–Sunday', hoursNote:'Dine-in hours may differ. Please call before visiting.', faqTitle:'Before your first bite.', faqs:[['How do I order delivery?','Open our Wolt listing to check delivery availability, the full menu and estimated waiting time.'],['How can I reserve a table?','Call +48 515 299 000 and ask about table availability.'],['Where can I check allergens?','Ask the team about ingredients and allergens before ordering. Dish information is also available on Wolt.']], footer:'Sushi, wok and Asian flavours in Białystok.', demo:'Website concept · PlexRS', priceNote:'Prices from the public Wolt menu. Check the current offer when ordering.', skip:'Skip to content', language:'Language', fullMenu:'Full menu on Wolt' },
 ru: { nav:['Меню','О Kitsune','Контакты'], order:'Заказать на Wolt', eyebrow:'АЗИАТСКАЯ КУХНЯ · БЕЛОСТОК', title:['Азия ближе,','чем кажется.'], intro:'Суши, согревающие супы и блюда из вока. Найдите любимый вкус на Warszawska 1A или закажите доставку домой.', explore:'Посмотреть меню', call:'Позвонить нам', strip:['СУШИ','ВОК','РАМЕН','ТОМ ЯМ'], menuLabel:'ЧЕГО ХОЧЕТСЯ СЕГОДНЯ?', menuTitle:'Яркий вкус. Ваш выбор.', menuIntro:'Несколько блюд из нашего меню. Полный список, актуальные цены и доступность — на Wolt.', categories:['Всё','Суши','Вок','Супы','Закуски'], aboutLabel:'KITSUNE ASIA', aboutTitle:'Один стол. Много вкусов.', about:'От лосося и хрустящей темпуры до пад-тая с лаймом и ароматного том-яма. Выберите блюдо для себя или разделите суши за общим столом.', gallery:'Вкусы Kitsune', photo:'Фотографии из карточки Kitsune на Restaurant Guru.', visitLabel:'ПРИХОДИТЕ К НАМ', visitTitle:'До встречи в Белостоке.', address:'Адрес', phone:'Телефон', directions:'Построить маршрут', hours:'Часы доставки Wolt', weekdays:'Понедельник–четверг', weekend:'Пятница–воскресенье', hoursNote:'Часы работы зала могут отличаться. Позвоните перед визитом.', faqTitle:'Перед первым кусочком.', faqs:[['Как заказать доставку?','Откройте нашу страницу на Wolt, чтобы проверить доступность доставки, полное меню и время ожидания.'],['Как забронировать столик?','Позвоните по номеру +48 515 299 000 и уточните наличие свободных столиков.'],['Где узнать об аллергенах?','Перед заказом уточните состав и аллергены у сотрудников. Информация о блюдах также есть на Wolt.']], footer:'Суши, вок и азиатские вкусы в Белостоке.', demo:'Концепция сайта · PlexRS', priceNote:'Цены из публичного меню Wolt. Проверьте актуальное предложение при заказе.', skip:'Перейти к содержимому', language:'Язык', fullMenu:'Полное меню на Wolt' }
} as const;
export const dishes = [
 {category:1,price:57,name:['California z łososiem','Salmon California','Калифорния с лососем'],desc:['Łosoś, awokado, ogórek, serek, tobiko.','Salmon, avocado, cucumber, cream cheese, tobiko.','Лосось, авокадо, огурец, сливочный сыр, тобико.']},
 {category:1,price:55,name:['Hot ebi','Hot ebi','Хот эби'],desc:['Krewetka, serek, ogórek, tempura, tajski majo.','Shrimp, cream cheese, cucumber, tempura, Thai mayo.','Креветка, сливочный сыр, огурец, темпура, тайский майонез.']},
 {category:2,price:49,name:['Pad thai z kurczakiem i tofu','Chicken & tofu pad thai','Пад-тай с курицей и тофу'],desc:['Makaron ryżowy, orzeszki ziemne, limonka, kolendra.','Rice noodles, peanuts, lime and coriander.','Рисовая лапша, арахис, лайм и кинза.']},
 {category:2,price:50,name:['Wołowina po syczuańsku','Sichuan-style beef','Говядина по-сычуаньски'],desc:['Wołowina, warzywa, ryż i sos po syczuańsku.','Beef, vegetables, rice and Sichuan-style sauce.','Говядина, овощи, рис и сычуаньский соус.']},
 {category:3,price:50,name:['Tom yum','Tom yum','Том ям'],desc:['Owoce morza, mleko kokosowe, limonka, ryż.','Seafood, coconut milk, lime and rice.','Морепродукты, кокосовое молоко, лайм и рис.']},
 {category:3,price:50,name:['Miso ramen','Miso ramen','Мисо рамен'],desc:['Wieprzowina char siu, jajko, enoki, makaron ramen.','Char siu pork, egg, enoki and ramen noodles.','Свинина чар сиу, яйцо, эноки и лапша рамен.']},
 {category:4,price:51,name:['Krewetki w tempurze','Tempura shrimp','Креветки в темпуре'],desc:['7 sztuk, z sosem sweet chilli.','7 pieces, served with sweet chilli sauce.','7 штук с соусом сладкий чили.']},
 {category:1,price:66,name:['Royal Dragon','Royal Dragon','Роял Драгон'],desc:['Krewetka w tempurze, węgorz, teriyaki, nerkowce.','Tempura shrimp, eel, teriyaki and cashews.','Креветка в темпуре, угорь, терияки и кешью.']}
];
