'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, MapPin, Phone, Plus, Utensils, X, Menu } from 'lucide-react';
import { dictionary, dishes, type Locale } from './dictionary';
const wolt='https://wolt.com/en/pol/bialystok/restaurant/kitsune-biaystok';
const base=process.env.NEXT_PUBLIC_BASE_PATH || '';
export default function Home(){
 const [locale,setLocale]=useState<Locale>('pl'); const [category,setCategory]=useState(0); const [mobile,setMobile]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('kitsune-language');if(saved==='pl'||saved==='en'||saved==='ru')setLocale(saved)},[]);
 useEffect(()=>{document.documentElement.lang=locale;localStorage.setItem('kitsune-language',locale)},[locale]);
 const t=dictionary[locale];const li={pl:0,en:1,ru:2}[locale];
 return <><a className="skip" href="#main">{t.skip}</a><header className="header"><a className="brand" href="#"><img className="brand-mark" src={`${base}/images/kitsune-emblem-v2.png`} alt="" width={72} height={72}/><span>KITSUNE<small>ASIA KITCHEN</small></span></a><nav className={mobile?'navigation opened':'navigation'} aria-label={t.language}><a href="#menu" onClick={()=>setMobile(false)}>{t.nav[0]}</a><a href="#about" onClick={()=>setMobile(false)}>{t.nav[1]}</a><a href="#visit" onClick={()=>setMobile(false)}>{t.nav[2]}</a></nav><div className="header-tools"><div className="languages" aria-label={t.language}>{(['pl','en','ru'] as Locale[]).map(l=><button key={l} lang={l} aria-pressed={locale===l} onClick={()=>setLocale(l)}>{l.toUpperCase()}</button>)}</div><a className="button small header-order" href={wolt} target="_blank" rel="noopener noreferrer">{t.order}</a><button className="mobile-toggle" aria-label={t.nav[0]} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></header>
 <main id="main"><div className="hero-wrap shell"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span/> {t.eyebrow}</p><h1>{t.title[0]}<br/><em>{t.title[1]}</em></h1><p className="lead">{t.intro}</p><div className="actions"><a className="button" href="#menu">{t.explore}<Utensils size={18}/></a><a className="text-link" href="tel:+48515299000">{t.call}</a></div><a className="hero-address" href="#visit"><MapPin size={17}/> Warszawska 1A, Białystok</a></div><div className="hero-visual"><img className="hero-photo" src={`${base}/images/california.png`} alt={dishes[0].name[li]} width={1200} height={675} fetchPriority="high"/><div className="photo-tag"><span className="tag-rule"/>{dishes[0].name[li]}<small>KITSUNE ASIA · BIAŁYSTOK</small></div></div></section></div>
 <div className="flavour-strip shell" aria-hidden="true">{t.strip.map((s,i)=><span key={i}><b>·</b>{s}</span>)}</div>
 <section id="menu" className="section menu-section shell"><div className="section-top"><div><p className="eyebrow">{t.menuLabel}</p><h2>{t.menuTitle}</h2></div><p>{t.menuIntro}</p></div><div className="filters" aria-label={t.nav[0]}>{t.categories.map((c,i)=><button key={c} onClick={()=>setCategory(i)} aria-pressed={category===i}>{c}</button>)}</div><div className="menu-grid">{dishes.filter(d=>category===0||d.category===category).map(d=><article className="dish" key={d.name[0]}><div className="dish-top"><span className="dish-kind">{t.categories[d.category]}</span><span className="dish-number">{String(dishes.indexOf(d)+1).padStart(2,'0')}</span></div><div className="dish-title"><h3>{d.name[li]}</h3><strong>{d.price}<small> zł</small></strong></div><p>{d.desc[li]}</p></article>)}</div><div className="menu-bottom"><p>{t.priceNote}</p><a href={wolt} className="text-link" target="_blank" rel="noopener noreferrer">{t.fullMenu}<ArrowUpRight size={17}/></a></div></section>
 <section id="about" className="about section shell"><div className="about-photos"><figure className="about-photo"><img src={`${base}/images/pad-thai.png`} alt={dishes[2].name[li]} width={1200} height={675} loading="lazy"/><figcaption>{dishes[2].name[li]}</figcaption></figure><figure className="about-photo secondary"><img src={`${base}/images/tom-yum.png`} alt={dishes[4].name[li]} width={1200} height={675} loading="lazy"/><figcaption>{dishes[4].name[li]}</figcaption></figure></div><div className="about-copy"><p className="eyebrow">{t.aboutLabel}</p><h2>{t.aboutTitle}</h2><p className="lead">{t.about}</p><a className="button" href={wolt} target="_blank" rel="noopener noreferrer">{t.order}<Utensils size={18}/></a><p className="photo-credit"><a href={wolt} target="_blank" rel="noopener noreferrer">{t.photo}</a></p></div></section>
 <section id="visit" className="visit shell"><div className="visit-panel section"><p className="eyebrow">{t.visitLabel}</p><h2>{t.visitTitle}</h2><div className="visit-grid"><div><span className="detail-label">{t.address}</span><p className="address">Warszawska 1A<br/>15-062 Białystok</p><a className="button dark" href="https://www.google.com/maps/search/?api=1&query=Kitsune+Warszawska+1A+Bialystok" target="_blank" rel="noopener noreferrer">{t.directions}<MapPin size={18}/></a></div><div><span className="detail-label">{t.phone}</span><a className="telephone" href="tel:+48515299000">+48 515 299 000</a><a className="contact-link" href="tel:+48515299000"><Phone size={17}/>{t.call}</a></div><div><span className="detail-label">{t.hours}</span><div className="hours"><p><span>{t.weekdays}</span><strong>12:00–20:30</strong></p><p><span>{t.weekend}</span><strong>12:00–21:30</strong></p></div><p className="hours-note">{t.hoursNote}</p></div></div></div></section>
 <section className="section shell faq"><div><p className="eyebrow">FAQ</p><h2>{t.faqTitle}</h2></div><div>{t.faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></section></main>
 <footer className="shell footer"><div><a href="#" className="footer-word"><img src={`${base}/images/kitsune-emblem-v2.png`} alt="" width={72} height={72}/>KITSUNE</a><p>{t.footer}</p></div><div className="footer-links"><a href={wolt} target="_blank" rel="noopener noreferrer">Wolt<ArrowUpRight size={15}/></a><a href="tel:+48515299000">+48 515 299 000</a><a href="https://demo.plexrs.com/">{t.demo}</a></div></footer></>
}
